[package]
name = "day-09"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = { workspace = true }
rstest = { workspace = true }
itertools = { workspace = true }
color-eyre = { workspace = true }
tokio = { workspace = true }
util = { workspace = true }
geo = "0.32.0"
image = "0.25.9"
